image:
  name: registry.gitlab.com/dreae/sourcemod-build:latest
  entrypoint: ["/bin/bash", "-c"]

build:
  script:
  - cp src/include/SteamWorks.inc /sourcemod/scripting/include
  - /sourcemod/scripting/spcomp -o discord_reports src/plugin.sp
  artifacts:
    paths:
      - discord_reports.smx
